config: common: add basic support for IPv6 setups

diff --git a/config/common/files/etc/uci-defaults/9902-network b/config/common/files/etc/uci-defaults/9902-network
--- a/config/common/files/etc/uci-defaults/9902-network
+++ b/config/common/files/etc/uci-defaults/9902-network
@@ -1,37 +1,35 @@
-uci batch << EOI
-
 # Global options
 {{- if has .network.globals "ula_prefix" }}
-set network.globals.ula_prefix='{{ .network.globals.ula_prefix }}'
+uci set network.globals.ula_prefix='{{ .network.globals.ula_prefix }}'
 {{- end }}
 {{- if has .network.globals "packet_steering" }}
 {{- if .network.globals.packet_steering }}
-set network.globals.packet_steering='1'
+uci set network.globals.packet_steering='1'
 {{ else }}
-set network.globals.packet_steering='0'
+uci set network.globals.packet_steering='0'
 {{- end }}
 {{- end }}
 
 {{- if has . "bridge_config" }}
-del network.@device[0].ports
+uci del network.@device[0].ports
 {{- range .bridge_config.ports }}
-add_list network.@device[0].ports='{{ . }}'
+uci add_list network.@device[0].ports='{{ . }}'
 {{- end }}
 {{- if .bridge_config.empty }}
-set network.@device[0].bridge_empty='1'
+uci set network.@device[0].bridge_empty='1'
 {{ else }}
-set network.@device[0].bridge_empty='0'
+uci set network.@device[0].bridge_empty='0'
 {{- end }}
 {{- end }}
 
 # Set up VLANs
 {{ range $name, $config := .networks }}
 {{- if has $config "vlan" }}
-set network.bridge_vlan_{{ print $name }}='bridge-vlan'
-set network.bridge_vlan_{{ print $name }}.device='{{ $config.device }}'
-set network.bridge_vlan_{{ print $name }}.vlan='{{ $config.vlan.id }}'
+uci set network.bridge_vlan_{{ print $name }}='bridge-vlan'
+uci set network.bridge_vlan_{{ print $name }}.device='{{ $config.device }}'
+uci set network.bridge_vlan_{{ print $name }}.vlan='{{ $config.vlan.id }}'
 {{- range $config.vlan.ports }}
-add_list network.bridge_vlan_{{ print $name }}.ports='{{ . }}'
+uci add_list network.bridge_vlan_{{ print $name }}.ports='{{ . }}'
 {{- end }}
 {{- end }}
 {{ end }}
@@ -39,31 +37,36 @@ add_list network.bridge_vlan_{{ print $name }}.ports='{{ . }}'
 # Set up networks
 {{ range $name, $config := .networks }}
 # delete network.{{ print $name }}
-set network.{{ print $name }}=interface
-set network.{{ print $name }}.proto='{{ $config.proto }}'
+uci set network.{{ print $name }}=interface
+uci set network.{{ print $name }}.proto='{{ $config.proto }}'
 {{- if eq $config.proto "static" }}
-set network.{{ print $name }}.ipaddr='{{ $config.ipaddr }}'
-set network.{{ print $name }}.gateway='{{ $config.gateway }}'
-set network.{{ print $name }}.netmask='{{ $config.netmask }}'
+uci set network.{{ print $name }}.ipaddr='{{ $config.ipaddr }}'
+uci set network.{{ print $name }}.gateway='{{ $config.gateway }}'
+uci set network.{{ print $name }}.netmask='{{ $config.netmask }}'
 {{- end }}
 {{- if has $config "vlan" }}
-set network.{{ print $name }}.device='{{ $config.device }}.{{ $config.vlan.id }}'
-{{ else }}
-set network.{{ print $name }}.device='{{ $config.device }}'
+uci set network.{{ print $name }}.device='{{ $config.device }}.{{ $config.vlan.id }}'
+{{- else }}
+uci set network.{{ print $name }}.device='{{ $config.device }}'
+{{- end }}
+{{- if has $config "ip6assign" }}
+uci set network.{{ print $name }}.ip6assign='{{ $config.ip6assign }}'
+{{- else }}
+# Do not fail, but still let us know something is off
+uci del network.{{ print $name }}.ip6assign || true
 {{- end }}
 {{- if has $config "type" }}
-set network.{{ print $name }}.type='{{ $config.type }}'
+uci set network.{{ print $name }}.type='{{ $config.type }}'
 {{- end }}
 {{- if has $config "dns" }}
-del network.{{ print $name }}.dns
+uci del network.{{ print $name }}.dns
 {{- range $config.dns }}
-add_list network.{{ print $name }}.dns='{{ . }}'
+uci add_list network.{{ print $name }}.dns='{{ . }}'
 {{- end }}
 {{- end }}
 {{ end }}
 
-commit network
-EOI
+uci commit network
 
 /etc/init.d/network restart
 if [ -f /etc/init.d/odhcpd ]; then
diff --git a/config/common/files/etc/uci-defaults/9904-dhcp b/config/common/files/etc/uci-defaults/9904-dhcp
--- a/config/common/files/etc/uci-defaults/9904-dhcp
+++ b/config/common/files/etc/uci-defaults/9904-dhcp
@@ -1,20 +1,29 @@
 # In case we run this on a switch
 if [ -f /etc/init.d/dnsmasq ]; then
 
-uci batch << EOI
-set dhcp.@dnsmasq[0].server='{{ .dhcp.default_dns_server }}'
+uci set dhcp.@dnsmasq[0].server='{{ .dhcp.default_dns_server }}'
 
 {{ range $name, $config := .networks }}
 {{- if has $config "dhcp" }}
-set dhcp.{{ print $name }}=dhcp
-set dhcp.{{ print $name }}.interface='{{ $name }}'
-set dhcp.{{ print $name }}.start='{{ $config.dhcp.start }}'
-set dhcp.{{ print $name }}.limit='{{ $config.dhcp.limit }}'
-set dhcp.{{ print $name }}.leasetime='{{ $config.dhcp.leasetime }}'
+uci set dhcp.{{ print $name }}=dhcp
+uci set dhcp.{{ print $name }}.interface='{{ $name }}'
+uci set dhcp.{{ print $name }}.start='{{ $config.dhcp.start }}'
+uci set dhcp.{{ print $name }}.limit='{{ $config.dhcp.limit }}'
+uci set dhcp.{{ print $name }}.leasetime='{{ $config.dhcp.leasetime }}'
+{{- if has $config.dhcp "ra" }}
+uci set dhcp.{{ print $name }}.ra='{{ $config.dhcp.ra }}'
+{{- end }}
+{{- if has $config.dhcp "dhcpv6" }}
+uci set dhcp.{{ print $name }}.dhcpv6='{{ $config.dhcp.dhcpv6 }}'
+{{- end }}
 {{- if has $config.dhcp "ra_flags" }}
-del dhcp.{{ print $name }}.ra_flags
+# Do not fail, but still let us know something is off
+uci del dhcp.{{ print $name }}.ra_flags || true
 {{- range $config.dhcp.ra_flags }}
-add_list dhcp.{{ print $name }}.ra_flags='{{ . }}'
+uci add_list dhcp.{{ print $name }}.ra_flags='{{ . }}'
+{{- end }}
+{{- if has $config.dhcp "ra_default" }}
+uci set dhcp.{{ print $name }}.ra_default='{{ $config.dhcp.ra_default }}'
 {{- end }}
 {{- end }}
 {{- end }}
@@ -22,34 +31,33 @@ add_list dhcp.{{ print $name }}.ra_flags='{{ . }}'
 
 {{ range $name, $config := .dhcp.hosts }}
 {{ $sanitized_name := strings.ReplaceAll "-" "_" $name }}
-set dhcp.{{ print $sanitized_name }}=host
-set dhcp.{{ print $sanitized_name }}.mac='{{ $config.mac }}'
-set dhcp.{{ print $sanitized_name }}.ip='{{ $config.ip }}'
-set dhcp.{{ print $sanitized_name }}.name='{{ $name }}'
+uci set dhcp.{{ print $sanitized_name }}=host
+uci set dhcp.{{ print $sanitized_name }}.mac='{{ $config.mac }}'
+uci set dhcp.{{ print $sanitized_name }}.ip='{{ $config.ip }}'
+uci set dhcp.{{ print $sanitized_name }}.name='{{ $name }}'
 {{ if has $config "dns" -}}
 {{ if $config.dns -}}
-set dhcp.{{ print $sanitized_name }}.dns='1'
+uci set dhcp.{{ print $sanitized_name }}.dns='1'
 {{ else }}
-set dhcp.{{ print $sanitized_name }}.dns='0'
+uci set dhcp.{{ print $sanitized_name }}.dns='0'
 {{ end -}}
 {{ end -}}
 {{ end }}
 
 {{- range $name, $config := .dhcp.domains }}
 {{ $sanitized_name := strings.ReplaceAll "." "_" $name }}
-set dhcp.{{ print $sanitized_name }}=domain
-set dhcp.{{ print $sanitized_name }}.ip='{{ $config.ip }}'
-set dhcp.{{ print $sanitized_name }}.name='{{ $name }}'
+uci set dhcp.{{ print $sanitized_name }}=domain
+uci set dhcp.{{ print $sanitized_name }}.ip='{{ $config.ip }}'
+uci set dhcp.{{ print $sanitized_name }}.name='{{ $name }}'
 {{- end }}
 
 {{ range $name, $config := coll.Merge .dhcp.addresses_ha .dhcp.addresses }}
 {{- range $config }}
-add_list dhcp.@dnsmasq[0].address='/{{ print $name }}/{{ . }}'
+uci add_list dhcp.@dnsmasq[0].address='/{{ print $name }}/{{ . }}'
 {{- end }}
 {{ end }}
 
-commit dhcp
-EOI
+uci commit dhcp
 
 fi
 
